export const flirtyLines = [
  "Are you a magician? Because whenever I look at you, everyone else disappears.",
  "Do you have a map? I keep getting lost in your eyes.",
  "Is your name Google? Because you have everything I've been searching for.",
  "Do you believe in love at first sight, or should I walk by again?",
  "Are you a parking ticket? Because you've got FINE written all over you.",
  "Is it hot in here? Or is it just you?",
  "If you were a vegetable, you'd be a cute-cumber.",
  "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
  "Are you a camera? Because every time I look at you, I smile.",
  "Can I follow you home? Cause my parents always told me to follow my dreams.",
  "Are you Wi-Fi? Because I'm feeling a connection.",
  "If beauty were time, you'd be an eternity.",
  "Do you have a name, or can I call you mine?",
  "Are you a time traveler? Because I see you in my future.",
  "Is your dad a boxer? Because you're a knockout!",
  "Do you have a sunburn, or are you always this hot?",
  "Are you a bank loan? Because you've got my interest.",
  "If I could rearrange the keyboard, I'd put U and I together.",
  "Are you French? Because Eiffel for you.",
  "Do you play soccer? Because you're a keeper.",
  "Are you a lightbulb? Because you brighten up my day.",
  "If looks could kill, you'd be a weapon of mass destruction.",
  "Are you a dictionary? Because you add meaning to my life.",
  "Do you have a quarter? Because I want to call my mom and tell her I met the one.",
  "Are you a beaver? Because daaaaam!",
  "Do you have a pencil? Because I want to erase your past and write our future.",
  "Are you a volcano? Because I lava you.",
  "Do you like Star Wars? Because Yoda one for me.",
  "Are you Australian? Because you meet all of my koala-fications.",
  "Are you a 45-degree angle? Because you're acute-y.",
  "Do you have a tan, or do you always look this hot?",
  "Are you a cat? Because you're purrfect.",
  "If I had four quarters to give to the four prettiest women in the world, you would have a dollar.",
  "Are you Siri? Because you autocomplete me.",
  "Are you a tower? Because Eiffel for you.",
  "Do you like Nintendo? Because Wii would look good together.",
  "Are you a banana? Because I find you a-peeling.",
  "If you were a triangle, you'd be acute one.",
  "Are you a keyboard? Because you're just my type.",
  "Do you like science? Because I've got my ion you.",
  "Are you religious? Because you're the answer to all my prayers.",
  "If beauty were a crime, you'd be serving a life sentence.",
  "Are you a snowstorm? Because you're making my heart race.",
  "Do you have a mirror in your pocket? Because I can see myself in your pants.",
  "Are you a campfire? Because you're hot and I want more.",
  "If kisses were snowflakes, I'd send you a blizzard.",
  "Are you a baker? Because you've got some nice buns.",
  "Do you like coffee? Because I like you a latte.",
  "Are you a chocolate bar? Because you're sweet and I want you.",
  "If you were a booger, I'd pick you first.",
  "Are you electricity? Because you're lighting up my life.",
  "Do you have a jersey? Because I need your name and number.",
  "Are you a thief? Because you stole my heart from across the room.",
  "If you were a song, you'd be the best track on the album.",
  "Are you a fruit? Because honeydew you know how fine you look right now?",
  "Do you have a name? Or can I just call you mine forever?",
  "Are you made of copper and tellurium? Because you're Cu-Te.",
  "If you were words on a page, you'd be fine print.",
  "Are you a garden? Because I'm digging you.",
  "Do you have a map? I just got lost in your smile.",
  "Are you a diamond? Because you're rare and valuable.",
  "If beauty were a drop of water, you'd be an ocean.",
  "Are you a rainbow? Because you're the treasure I've been looking for.",
  "Do you have a license? Because you're driving me crazy.",
  "Are you an artist? Because you just painted a smile on my face.",
  "If you were a dessert, you'd be a hot fudge sundae with a cherry on top.",
  "Are you a chef? Because you've got all the right ingredients.",
  "Do you like music? Because you're making my heart sing.",
  "Are you a detective? Because I'm guilty of falling for you.",
  "If you were a season, you'd be summer - hot and unforgettable.",
  "Are you a firework? Because you light up my sky.",
  "Do you like astronomy? Because you're out of this world.",
  "Are you a comet? Because you're rare and I'm lucky to see you.",
  "If I were a cat, I'd spend all nine lives with you.",
  "Are you gravity? Because I'm falling for you and can't get up.",
  "Do you have a compass? Because I'm lost without you.",
  "Are you an alarm clock? Because I want to wake up to you every morning.",
  "If you were a movie, you'd be a romantic comedy - funny and heartwarming.",
  "Are you a photographer? Because I can picture us together forever.",
  "Do you believe in magic? Because you've cast a spell on me.",
  "Are you a pilot? Because you make my heart soar.",
  "If life were a puzzle, you'd be the missing piece.",
  "Are you a snowflake? Because you're one of a kind.",
  "Do you have a watch? Because I want to spend time with you.",
  "Are you a bookmark? Because I want to keep you in my story.",
  "If you were a car, you'd be a Ferrari - fast, sleek, and stunning.",
  "Are you a sunrise? Because you make every day better.",
  "Do you like adventure? Because exploring life with you would be perfect.",
  "Are you a cupcake? Because you're sweet and I want a taste.",
  "Do you have WiFi? Because I'm really feeling a connection.",
  "Are you my phone charger? Because without you, I'd die.",
  "If you were a vegetable, you'd be a cute-cumber!",
  "Are you a loan from a bank? Because you have my interest.",
  "Do you have a Band-Aid? I just scraped my knee falling for you.",
  "Are you a time traveler? Because I absolutely see you in my future.",
  "Is your name Ariel? Because we mermaid for each other.",
  "Are you from Tennessee? Because you're the only 10 I see.",
  "Do you have a sunburn or are you always this hot?",
  "If kisses were stars, I'd give you the whole galaxy.",
  "Are you Netflix? Because I could watch you for hours.",
  "Do you like raisins? How do you feel about a date?",
  "Are you a 90-degree angle? Because you are looking right!",
  "If you were a chicken, you'd be impeccable.",
  "Are you a melody? Because I can't get you out of my head.",
  "Do you have a twin? Because you are one of a kind!",
  "Are you made of grapes? Because you are fine as wine.",
  "If I could rearrange the stars, I'd put U and I together.",
  "Are you a flower? Because I'm falling for your petals.",
  "Do you have a nickname? Because I want to call you mine.",
  "Are you a library card? Because I'm checking you out.",
  "If you were a flower, you'd be a damn-delion.",
  "Are you a dream? Because I never want to wake up.",
  "Do you know CPR? Because you take my breath away.",
  "Are you a piece of art? Because you are a masterpiece.",
  "If love was illegal, would you be my partner in crime?",
  "Are you oxygen? Because I need you to breathe.",
  "Do you like smoothies? Because you blend perfectly into my life.",
  "Are you a sunset? Because you make everything beautiful.",
  "If I had a dollar for every time I thought of you, I'd be a millionaire.",
  "Are you a spell? Because you've enchanted me.",
  "Do you believe in fate? Because I think we're meant to be.",
  "Are you the ocean? Because I'm drowning in your eyes.",
  "If you were a cat, you'd purr-fectly fit in my life.",
  "Are you a novel? Because I can't put you down.",
  "Do you like games? Because I think we'd be a perfect match.",
  "Are you a star? Because you light up my universe.",
  "If I were a superhero, my superpower would be making you smile.",
  "Are you a recipe? Because you have all the right ingredients.",
  "Do you have an eraser? Because I can't get you out of my mind.",
  "Are you autumn? Because you make me fall.",
  "If you were a planet, you'd be heaven.",
  "Are you a poet? Because you make my heart sing verses.",
  "Do you like puzzles? Because I think you're my missing piece.",
  "Are you a door? Because I'm a-door-able when I'm with you.",
  "If you were ice cream, you'd be my favorite flavor.",
  "Are you a candle? Because you light up my life.",
  "Do you have a mirror? Because I see myself in your future.",
  "Are you destiny? Because I feel like we're meant to meet.",
  "If you were a superhero, you'd be Super Cute.",
  "Are you a gem? Because you're rare and precious.",
  "Do you play guitar? Because you're striking all the right chords.",
  "Are you breakfast? Because you're the most important part of my day.",
  "If you were a grade, you'd be an A+.",
  "Are you a magnet? Because I'm attracted to you.",
  "Do you like honey? Because you're the bee's knees.",
  "Are you a fountain? Because my love for you flows endlessly.",
  "If you were a spice, you'd be cinnamon - sweet and hot.",
  "Are you a dancer? Because you make my heart skip a beat.",
  "Do you have insurance? Because you've got fine written all over you.",
  "Are you a coin? Because you're a rare find.",
  "If life is a highway, I want to ride it all night with you.",
  "Are you a firework? Because you make my heart explode with joy.",
  "Do you like sweets? Because you're sweeter than candy.",
  "Are you a crown? Because you reign in my heart.",
  "If I had a flower for every time you made me smile, I'd have a garden.",
  "Are you an angel? Because heaven is missing one.",
  "Do you have a passport? Because you've traveled straight to my heart.",
  "Are you a rocket? Because you take me to new heights.",
  "If beauty were currency, you'd be the richest person alive.",
  "Are you a sunset view? Because I could look at you forever.",
  "Do you like chocolate? Because you're sweet and irresistible.",
  "Are you Wi-Fi? Because I'm feeling a strong connection.",
  "If I could give you one thing, it would be the ability to see yourself through my eyes.",
  "Are you a fortune? Because you're my treasure.",
  "Do you like adventures? Because you're the greatest one I've ever known.",
  "Are you a shooting star? Because I want to make a wish on you.",
  "If kisses were water, I'd give you the ocean.",
  "Are you sugar? Because you make life sweet.",
  "Do you believe in miracles? Because you're looking at one.",
  "Are you today's date? Because you're 10/10.",
  "If you were a season, you'd make every day feel like spring.",
  "Are you champagne? Because you're making me bubbly inside.",
  "Do you have a watch? Because I want to spend every second with you.",
  "Are you a melody? Because you're stuck in my head in the best way.",
  "If you were a drink, you'd be a hot chocolate - warm and sweet.",
  "Are you a painter? Because you color my world.",
  "Do you like stargazing? Because you're the brightest star I see.",
  "Are you a page in a book? Because I can't wait to turn to you.",
  "If I could describe you in one word, it would be perfect.",
  "Are you a butterfly? Because you give me butterflies.",
  "Do you like poetry? Because you're the poem I want to write.",
  "Are you winter? Because you give me chills in the best way.",
  "If smiles were hugs, I'd hold you forever.",
  "Are you a wish? Because you're the one I've been waiting for.",
  "Do you like roses? Because you're more beautiful than a garden full.",
  "Are you spring? Because you make everything bloom.",
  "If I had to choose between breathing and loving you, I'd use my last breath to say I love you.",
  "Are you the key? Because you unlock my heart.",
  "Do you have a favorite song? Because you're my favorite melody.",
  "Are you a promise? Because I want to keep you forever.",
  "If you were a memory, you'd be my favorite one.",
  "Are you luck? Because I feel lucky to know you.",
  "Do you like moonlight? Because you shine brighter than it.",
  "Are you a whisper? Because I want to listen to you all day.",
  "If I could bottle up your smile, I'd be rich beyond measure.",
  "Are you a compass? Because you always point me in the right direction.",
  "Do you like sunsets? Because you're more stunning than any I've seen.",
  "Are you hope? Because you make me believe in tomorrow.",
  "If you were a moment, you'd be my favorite second of every day.",
  "Are you a heartbeat? Because you keep me alive.",
  "Do you like jazz? Because you make my heart swing.",
  "Are you serendipity? Because meeting you was the best accident.",
  "If you were a color, you'd be the most vibrant shade.",
  "Are you a photograph? Because I want to capture this moment forever.",
  "Do you like adventures? Because loving you is the greatest journey.",
  "Are you a secret? Because I want to keep you close to my heart.",
  "If you were a dance, you'd be a beautiful waltz.",
  "Are you a breeze? Because you take my breath away.",
  "Do you like sunrises? Because you're the dawn of my new beginning.",
  "Are you laughter? Because you're the best sound I've ever heard.",
  "If you were happiness, you'd be every smile I've ever had.",
  "Are you a dream come true? Because you're exactly what I wished for.",
  "Do you like mysteries? Because I want to spend forever discovering you.",
  "Are you a serenade? Because you're music to my ears.",
  "If you were peace, you'd be the calm after every storm.",
  "Are you magic? Because everything changes when you're around.",
  "Do you like rainbows? Because you're my pot of gold.",
  "Are you joy? Because you're the happiness in my life.",
  "If you were a feeling, you'd be love itself.",
  "Are you a treasure map? Because X marks the spot where my heart is.",
  "Do you like fairytales? Because ours could be the best one ever written.",
  "Are you perfection? Because that's what I see when I look at you.",
  "If you were a word, you'd be extraordinary.",
  "Are you a symphony? Because you're a masterpiece of sound.",
  "Do you like starlight? Because you outshine them all.",
  "Are you wonder? Because I'm in awe of you.",
  "If you were a journey, you'd be the adventure of a lifetime.",
  "Are you a blessing? Because you're the answer to my prayers.",
  "Do you like magic shows? Because you make the impossible seem real.",
  "Are you grace? Because you move through life beautifully.",
  "If you were time, I'd want you to last forever.",
  "Are you silk? Because you're smooth and precious.",
  "Do you like fireworks? Because you make my heart burst with color.",
  "Are you art? Because you're too beautiful for words.",
  "If you were sunshine, you'd warm every cold day.",
  "Are you eternity? Because I want forever with you.",
  "Do you like stories? Because I want you in every chapter of mine.",
  "Are you bliss? Because that's what I feel when you're near.",
  "If you were music, you'd be my favorite song on repeat.",
  "Are you radiance? Because you glow from within.",
  "Do you like moments? Because every second with you is precious.",
  "Are you infinity? Because my love for you knows no end.",
  "If you were courage, you'd be the bravery in my heart.",
  "Are you serenity? Because you bring me peace.",
  "Do you like whispers? Because yours is the only voice I want to hear.",
  "Are you essence? Because you're the core of my happiness.",
  "If you were a promise, you'd be the one I'd never break.",
  "Are you moonlight? Because you illuminate my darkest nights.",
  "Do you like horizons? Because you're my endless possibility.",
  "Are you velvet? Because you're soft and luxurious to my soul.",
  "If you were a breath, you'd be the one that sustains me.",
  "Are you wonder? Because discovering you is my greatest adventure.",
  "Do you like echoes? Because your voice resonates in my heart.",
  "Are you crystal? Because you're clear, pure, and valuable.",
  "If you were a touch, you'd be the one that heals everything.",
  "Are you poetry in motion? Because watching you is like reading the finest verse.",
  "Do you like constellations? Because you're my guiding stars.",
  "Are you tranquility? Because you calm every storm within me.",
  "If you were a season, you'd be eternal spring - always bringing new life.",
  "Are you amber? Because you preserve the most precious moments.",
  "Do you like gardens? Because you make beautiful things grow in my heart.",
  "Are you a gentle rain? Because you're refreshing to my soul.",
  "If you were wisdom, you'd be the truth I seek.",
  "Are you a soft melody? Because you soothe everything within me.",
  "Do you like symphonies? Because you orchestrate joy in my life.",
  "Are you dewdrops? Because you're delicate beauty at dawn.",
  "If you were a canvas, you'd be painted with the colors of dreams.",
  "Are you vintage? Because you're timeless and precious.",
  "Do you like twilight? Because you're the magic between day and night.",
  "Are you an heirloom? Because you're meant to be treasured forever.",
  "If you were a whisper of wind, you'd be the gentle breeze of comfort.",
  "Are you porcelain? Because you're delicate yet strong.",
  "Do you like crescendos? Because you're the peak of my emotions.",
  "Are you silk and honey? Because you're smooth sweetness.",
  "If you were a lullaby, you'd be the song that brings peace.",
  "Are you opalescent? Because you shimmer with hidden beauty.",
  "Do you like waltzes? Because dancing through life with you would be elegant.",
  "Are you luminescence? Because you glow with inner light.",
  "If you were a masterpiece, you'd hang in the gallery of my heart.",
  "Are you morning glory? Because you're the first beautiful thing I want to see.",
  "Do you like crescents? Because you're my new beginning.",
  "Are you golden hour? Because everything's more beautiful with you.",
  "If you were a treasure chest, you'd hold all my hopes and dreams.",
  "Are you a pearl? Because you're formed from something beautiful and rare.",
  "Do you like harmonies? Because we create perfect music together.",
  "Are you cashmere? Because you're luxurious comfort.",
  "If you were an emerald, you'd be the most precious gem.",
  "Are you a sonnet? Because you're poetic perfection.",
  "Do you like ballads? Because our story could be sung for ages.",
  "Are you lavender? Because you bring calm and beauty.",
  "If you were a vintage wine, you'd only get better with time.",
  "Are you stardust? Because you're made of cosmic magic.",
  "Do you like mosaics? Because every part of you creates something beautiful.",
  "Are you alabaster? Because you're pure and exquisite.",
  "If you were a garden path, I'd walk it forever.",
  "Are you crystalline? Because you're clear beauty.",
  "Do you like reveries? Because thinking of you is my favorite daydream.",
  "Are you satin? Because you're smooth elegance.",
  "If you were a lighthouse, you'd guide me through every storm.",
  "Are you prismatic? Because you reveal beauty in every angle.",
  "Do you like ballrooms? Because you make my heart dance.",
  "Are you celestial? Because you're heavenly.",
  "If you were a melody box, I'd wind you up forever.",
  "Are you iridescent? Because you shine with changing beauty.",
  "Do you like serenades? Because I could sing your praises endlessly.",
  "Are you mahogany? Because you're rich and timeless.",
  "If you were a fountain, you'd be where wishes come true.",
];

export const poeticLines = [
  "Like the moon calls to the tide, I am drawn to you.",
  "In a sea of people, my eyes will always search for you.",
  "You're the poem I never knew how to write, and this life is the story I've always wanted to tell.",
  "If I could rearrange the alphabet, I'd put U and I together.",
  "Your smile must be a black hole, nothing can escape its pull.",
  "I'm not a photographer, but I can picture us together.",
  "You must be made of stardust because you light up my universe.",
  "Are you a work of art? Because I could admire you all day.",
  "Like a compass pointing north, I'm always drawn to you.",
  "You're the reason poets write and artists create.",
  "In the symphony of my life, you're the most beautiful melody.",
  "Your eyes hold galaxies I want to explore forever.",
  "If souls could dance, mine would waltz with yours eternally.",
  "You're the sunrise after my longest night.",
  "Like a constellation in the sky, you guide me home.",
  "Every heartbeat whispers your name in a language only I understand.",
  "You're the masterpiece in the museum of my dreams.",
  "Like rain on desert sand, you bring life to my world.",
  "In the garden of my thoughts, you bloom eternal.",
  "You're the missing verse in my favorite song.",
  "Like waves kissing the shore, I'm drawn to you endlessly.",
  "Your presence is poetry my heart learned to read.",
  "In the book of my life, you're the most beautiful chapter.",
  "You're the echo of every wish I've ever made.",
  "Like a meteor across the sky, you left me breathless.",
  "You're the dream I never want to wake from.",
  "Like autumn leaves, I fall for you more each day.",
  "In the tapestry of time, you're the golden thread.",
  "You're the lighthouse in my storm, guiding me safely home.",
  "Like a phoenix rising, you awakened my sleeping heart.",
  "You're the universe's way of showing me magic exists.",
  "In the silence between heartbeats, I hear your name.",
  "You're the answer to questions I didn't know I was asking.",
  "Like the first ray of dawn, you illuminate my darkness.",
  "You're the treasure at the end of every rainbow.",
  "In the gallery of souls, yours is the masterpiece.",
  "You're the reason the stars shine a little brighter.",
  "Like honey to the soul, your presence sweetens my existence.",
  "You're the canvas where all my dreams are painted.",
  "In the orchestra of life, you're the crescendo.",
  "You're the whisper of eternity in a fleeting moment.",
  "Like a pearl in the ocean, rare and precious you are.",
  "You're the magic hour when day kisses night.",
  "In the library of hearts, yours is the only book I want to read.",
  "You're the bridge between my reality and my dreams.",
  "Like champagne bubbles, you make everything effervescent.",
  "You're the compass rose on my map of life.",
  "In the currency of emotions, you're priceless.",
  "You're the secret ingredient that makes life delicious.",
  "Like a violin's first note, you resonate through my soul.",
  "You're the plot twist in my favorite story.",
  "In the architecture of destiny, you're the cornerstone.",
  "You're the encore I've been waiting for all my life.",
  "Like a river flowing to the sea, my soul journeys toward you.",
  "You're the bookmark in the novel of my existence.",
  "In the constellation of humanity, you're my North Star.",
  "You're the crescendo in my life's symphony.",
  "Like a butterfly emerging, you've transformed my world.",
  "You're the fragrance that lingers after the flower has bloomed.",
  "In the mosaic of moments, you're every precious tile.",
  "You're the horizon where my sky meets your earth.",
  "Like a vintage wine, thoughts of you improve with time.",
  "You're the sonnet Shakespeare forgot to write.",
  "In the garden of Eden, you're the forbidden fruit worth everything.",
  "You're the pause between thunder and lightning - electric anticipation.",
  "Like ancient ruins, you hold mysteries I want to spend lifetimes uncovering.",
  "You're the handwritten letter in an age of text messages.",
  "In the mathematics of love, you're the perfect equation.",
  "You're the fingerprint on my heart that no one else can leave.",
  "Like a prism splitting light, you reveal all of life's colors.",
  "You're the bookmark holding my place in paradise.",
  "In the language of flowers, you're the rarest bloom.",
  "You're the intermission I never want to end.",
  "Like sand through an hourglass, I want every grain of time with you.",
  "You're the signature on the masterpiece of my dreams.",
  "In the anthology of souls, yours is the poetry that moves me.",
  "You're the northern lights dancing in my night sky.",
  "Like a fountain in the desert, you quench my deepest thirst.",
  "You're the vintage record playing our song.",
  "In the museum of memories, you're the exhibit I revisit endlessly.",
  "You're the tide that moves the ocean of my emotions.",
  "Like a key to a hidden door, you unlock parts of me unknown.",
  "You're the cherry blossom - beautiful and fleeting, but unforgettable.",
  "In the script of destiny, you're the line I want to rehearse forever.",
  "You're the compass needle always pointing toward happiness.",
  "Like morning dew on petals, you're delicate perfection.",
  "You're the golden hour captured in human form.",
  "In the silence of snow falling, I hear echoes of your name.",
  "You're the ancient oak - strong, enduring, beautiful.",
  "Like a river carving canyons, you've shaped my very soul.",
  "You're the constellation I've been searching for my whole life.",
  "In the rhythm of rain, I find the beat of your heart.",
  "You're the solstice - the turning point of my seasons.",
  "Like smoke from incense, thoughts of you rise and linger.",
  "You're the meridian where all my longitudes converge.",
  "In the gallery of constellations, you're the brightest pattern.",
  "You're the vintage photograph that captures timeless beauty.",
  "Like moss on ancient stones, you've grown into my foundation.",
  "You're the aria that brings audiences to tears.",
  "In the lexicon of love, you're every word worth saying.",
  "You're the myth that turns out to be true.",
  "Like copper turning green, you age into something precious.",
  "You're the manuscript historians will treasure.",
  "In the taxonomy of beauty, you're a species unto yourself.",
  "You're the relic archaeologists dream of finding.",
  "Like a well-worn path, you're the journey I want to repeat.",
  "You're the melody cellos weep to play.",
  "In the cathedral of my heart, you're the stained glass.",
  "You're the folklore passed down through generations.",
  "Like footprints in wet sand, you've left your mark on me.",
  "You're the forgotten verse that makes the poem complete.",
  "In the anthology of existence, you're the foreword and epilogue.",
  "You're the patina that makes bronze more beautiful.",
  "Like ivy climbing walls, you've grown around my heart.",
  "You're the hidden track on my favorite album.",
  "In the manuscript of time, you're written in gold leaf.",
  "You're the secret garden behind locked gates.",
  "Like incense in a temple, you're sacred presence.",
  "You're the soliloquy that reveals all truth.",
  "In the atlas of emotions, you're the undiscovered country.",
  "You're the epilogue that changes everything before it.",
  "Like tide pools reflecting sky, you mirror infinity.",
  "You're the thesis every philosophy pursues.",
  "In the chronology of moments, you're the era I name.",
  "You're the vintage vinyl - crackles and all, perfect.",
  "Like morning fog lifting, you reveal daily miracles.",
  "You're the cornerstone of my cathedral.",
  "In the lexicon of longing, you're the only definition.",
  "You're the orchestral swell that gives me chills.",
  "Like ancient pottery, you're fragments made precious.",
  "You're the doctrine I devoutly follow.",
  "In the pantheon of people, you're the deity.",
  "You're the ballad sung around campfires for centuries.",
  "Like patina on silver, time makes you more valuable.",
  "You're the manuscript illuminated with gold.",
  "In the vocabulary of desire, you're fluent expression.",
  "You're the fable with the moral that changes lives.",
  "Like echoes in canyons, you amplify everything beautiful.",
  "You're the legend maps mark with an X.",
  "In the museum of souls, you're the crown jewel.",
  "You're the epilogue that makes readers weep.",
  "Like autumn's first frost, you transform everything you touch.",
  "You're the monologue that stops the show.",
  "In the codex of connection, you're every page.",
  "You're the metaphor poets spend lifetimes perfecting.",
  "Like bells in distant towers, you call me home.",
  "You're the anthology compiled from my favorite verses.",
  "In the geometry of grace, you're every elegant angle.",
  "You're the prologue that promises something wonderful.",
  "Like honeycomb filled with gold, you're sweet treasure.",
  "You're the symphony's finale that leaves silence sacred.",
  "In the cartography of souls, you're the compass rose.",
  "You're the legend in margins of ancient texts.",
  "Like morning glory opening at dawn, you reveal daily beauty.",
  "You're the sonata that pianists pray to master.",
  "In the registry of rare things, you're first entry.",
  "You're the parable wise ones repeat for generations.",
  "Like lighthouse beams cutting fog, you show the way.",
  "You're the manuscript monks labored years to create.",
  "In the encyclopedia of excellence, you fill volumes.",
  "You're the legend cartographers wrote in cursive.",
  "Like cathedral spires reaching skyward, you elevate everything.",
  "You're the aria sopranos build careers upon.",
  "In the compendium of completeness, you're the only entry.",
  "You're the doctrine prophets proclaim from mountains.",
  "Like vintage maps, you show places I want to discover.",
  "You're the ballad that makes warriors weep.",
  "In the anthology of amazement, you're every stanza.",
  "You're the legend librarians whisper about.",
  "Like morning mist in valleys, you're ethereal beauty.",
  "You're the overture that promises magnificence.",
  "In the dictionary of devotion, you define every word.",
  "You're the myth that makes believers of skeptics.",
  "Like carved jade handed down generations, you're precious heritage.",
  "You're the psalm sung in cathedrals for centuries.",
  "In the bibliography of beauty, you're the definitive work.",
  "You're the chronicle historians consider complete.",
  "Like pearls on silk thread, you're elegance strung together.",
  "You're the epic poem memorized by heart.",
  "In the catalog of wonders, you're the illustrated cover.",
  "You're the fable children request night after night.",
  "Like stained glass filtering light, you transform ordinary rays.",
  "You're the manuscript worth more than gold.",
  "In the register of remarkable, you're the heading.",
  "You're the legend teachers use to inspire.",
  "Like ancient ruins revealing glory, you show traces of the divine.",
  "You're the concerto conductors dream of performing.",
  "In the journal of joy, you're every entry.",
  "You're the parable that contains all wisdom.",
  "Like cathedral bells on Sunday morning, you call souls to beauty.",
  "You're the epic tale told around fires for ages.",
  "In the ledger of love, you're the only account.",
  "You're the doctrine worth defending.",
  "Like baroque architecture, you're ornate perfection.",
  "You're the verse that makes poetry matter.",
  "In the manifesto of meaning, you're every declaration.",
  "You're the myth that turns cynic into believer.",
  "Like calligraphy in gold ink, you're artistry itself.",
  "You're the chronicle worth preserving for eternity.",
  "In the registry of radiance, you're the signature entry.",
  "You're the legend maps note in careful script.",
  "Like organ music filling cathedrals, you resonate in my soul.",
  "You're the doctrine scholars debate for centuries.",
  "In the catalog of complete, you're the example.",
  "You're the fable philosophers reference.",
  "Like Byzantine mosaics, you're art made of precious pieces.",
  "You're the manuscript museums guard jealously.",
  "In the anthology of eternity, you're the opening verse.",
  "You're the legend that makes history worth studying.",
  "Like amber preserving ancient insects, you capture precious moments.",
  "You're the psalm that gives voice to devotion.",
  "In the lexicon of luminous, you're the definition.",
  "You're the epic poem worth years of study.",
  "Like Gothic cathedrals rising, you inspire awe.",
  "You're the chronicle future generations will treasure.",
  "In the compendium of completeness, you're the gold standard.",
  "You're the legend cartographers mark with reverence.",
  "Like venetian glass catching light, you're fragile magnificence.",
  "You're the doctrine that defines an age.",
  "In the registry of remarkable souls, you're first among equals.",
  "You're the myth that makes mortals believe in magic.",
  "Like illuminated manuscripts, you're art and meaning combined.",
  "You're the verse that validates the entire poem.",
  "In the catalog of celestial, you're the brightest star.",
  "You're the fable that carries truth through time.",
  "Like porcelain surviving dynasties, you're delicate strength.",
  "You're the chronicle historians cite as definitive.",
  "In the anthology of aspiration, you're what we reach for.",
  "You're the legend spoken in hushed, reverent tones.",
  "Like organs in empty cathedrals, you fill vast spaces with beauty.",
  "You're the psalm set to music by masters.",
  "In the bibliography of breathtaking, you're required reading.",
  "You're the epic tale that never grows old.",
  "Like frescoes on ancient ceilings, you're beauty overhead.",
  "You're the doctrine philosophers spend lifetimes unpacking.",
  "In the encyclopedia of enchanting, you're comprehensive.",
  "You're the myth that makes reality seem mundane.",
  "Like silk roads connecting empires, you bridge my past and future.",
  "You're the manuscript worth a kingdom's ransom.",
  "In the register of resplendent, you're the paradigm.",
  "You're the legend sailors navigate by.",
  "Like monastery bells at vespers, you mark the sacred hours.",
  "You're the chronicle that chronicles the best of everything.",
  "In the lexicon of longing, you're every word and definition.",
  "You're the verse that makes poets put down their pens in awe.",
  "Like Byzantine emperors, you rule my empire absolutely.",
  "You're the doctrine that converts nonbelievers.",
  "In the catalog of wonders, you're the limited edition.",
  "You're the fable elders tell to teach love itself.",
  "Like tapestries depicting battles, you're conflict resolved into beauty.",
  "You're the manuscript illuminators spent decades perfecting.",
  "In the anthology of angels, you're first among seraphim.",
  "You're the legend that gives meaning to the map.",
  "Like rose windows in Notre Dame, you're geometry and grace.",
  "You're the psalm I whisper in moments of pure gratitude.",
  "In the dictionary of dreams, you define them all.",
  "You're the epic odyssey worth every trial.",
  "Like jade handed through dynasties, you're heirloom beauty.",
  "You're the chronicle every historian wants to author.",
  "In the bibliography of blessed, you're the sacred text.",
  "You're the myth carved in marble for eternity.",
  "Like cathedral acoustics, you amplify the divine.",
  "You're the verse that justifies poetry's existence.",
  "In the compendium of completeness, you're the final word.",
  "You're the legend worth the quest.",
  "Like Gregorian chants echoing in stone halls, you're haunting beauty.",
  "You're the doctrine that defines devotion itself.",
  "In the registry of rare souls, you're priceless.",
  "You're the fable that makes children believe in happy endings.",
  "Like Ming vases in museums, you're protected perfection.",
  "You're the manuscript scholars make pilgrimages to see.",
  "In the anthology of all things, you're the dedication page.",
  "You're the legend adventurers chase to the ends of earth.",
  "Like spice roads bringing treasures, you're the precious cargo.",
  "You're the psalm that makes cathedrals necessary.",
  "In the lexicon of love, you wrote every entry.",
  "You're the epic poem that defines an era.",
  "Like masterwork clocks in towers, you mark time beautifully.",
  "You're the chronicle worth preserving in gold leaf.",
];

export const boldLines = [
  "Is it hot in here? Or is it just you?",
  "Do you work at Starbucks? Because I like you a latte.",
  "Are you my appendix? Because I don't understand how you work, but this feeling in my stomach makes me want to take you out.",
  "Do you like sales? Because if you're looking for a good one, clothing is 100% off at my place.",
  "Are you a loan? Because you've got my interest.",
  "I'm not a weatherman, but you can expect a few more inches tonight.",
  "Did you sit in a pile of sugar? Because you have a pretty sweet ass.",
  "Are you a sea lion? Because I can see you lion in my bed tonight.",
  "Is your body from McDonald's? Because I'm lovin' it.",
  "Are you a campfire? Because you're hot and I want s'more.",
  "Do you believe in karma? Because I know some good karma-sutra positions.",
  "Are you a magician? Because whenever I look at you, my clothes disappear.",
  "I'm not a genie, but I can make your dreams come true... at least the naughty ones.",
  "If you were a fruit, you'd be a fine-apple. And I'd want to take a bite.",
  "Are you a library book? Because I'm checking you out and I might be late returning you.",
  "Did it hurt? When you fell from the vending machine? Because you're a snack.",
  "Are you a charger? Because I'm dying without you.",
  "Is your name Chapstick? Because you're da balm.",
  "Do you work at Little Caesars? Because you're hot and I'm ready.",
  "Are you a firefighter? Because you're smoking hot and I need you to handle my emergency.",
  "If you were a triangle, you'd be acute one... and I'd love to find your angles.",
  "Are you homework? Because I should be doing you on my desk right now.",
  "Do you like raisins? How do you feel about a date?",
  "Are you a keyboard? Because you're just my type and I want to tap that.",
  "Is your body a temple? Because I'd worship at your altar all night long.",
  "Are you a blender? Because I want to put my smoothie in you.",
  "Do you like pizza? Because I want a pizza you tonight.",
  "Are you a construction worker? Because you're building up something in my pants.",
  "Is your dad a terrorist? Because you're the bomb and I want to defuse you with my hands.",
  "Are you a drill sergeant? Because you have my privates standing at attention.",
  "Do you work for UPS? Because I could swear I saw you checking out my package.",
  "Are you a microwave? Because you make my heart race in 30 seconds.",
  "Is there a mirror in your pants? Because I can see myself in them.",
  "Are you a light switch? Because you turn me on.",
  "Do you like whales? Because we can go hump back at my place.",
  "Are you a candle? Because I want to blow you.",
  "Do you like dragons? Because I'll be dragon my balls across your face tonight.",
  "Are you a washing machine? Because I want to put a load in you.",
  "Is your name winter? Because you'll be coming soon.",
  "Are you a roller coaster? Because the faster you go, the louder I scream.",
  "Do you like gardening? Because I want to plant my seed in your garden.",
  "Are you a haunted house? Because I'm going to scream when I'm inside you.",
  "Is your name Medusa? Because you make me rock hard.",
  "Are you a trampoline? Because I want to bounce on you.",
  "Do you believe in helping the homeless? Because I need a place to stay... in your bed.",
  "Are you a bottle of Tabasco? Because I want to put you on everything.",
  "Is your phone in your back pocket? Because your ass is calling me.",
  "Are you a mixer? Because you're getting me all stirred up.",
  "Do you like Subway? Because I'll give you a footlong.",
  "Are you an archaeologist? Because I've got a large bone for you to examine.",
  "Is your body a wonderland? Because I want to explore every inch.",
  "Are you a fortune cookie? Because I'm about to crack you open and eat what's inside.",
  "Do you like sales? Because clothes are 100% off at my place tonight.",
  "Are you a racecar? Because I want to ride you all day long.",
  "Is your name Google? Because you've got everything I'm searching for under the sheets.",
  "Are you a beaver? Because dam, I want to get in your lodge.",
  "Do you work at Subway? Because you just gave me a footlong.",
  "Are you a parking ticket? Because you've got fine written all over you and I want to pay you.",
  "Is your body a menu? Because I want to order everything on it.",
  "Are you a magnet? Because you're attracting me to your bed.",
  "Do you like yoga? Because you're about to get a good stretch.",
  "Are you a thermometer? Because you're making my temperature rise.",
  "Is your name Gillette? Because you're the best a man can get.",
  "Are you a tornado? Because you're blowing me away.",
  "Do you work at a brewery? Because you're making me feel tipsy.",
  "Are you a chiropractor? Because you're about to adjust my spine.",
  "Is your name Campbell? Because you're mm-mm good.",
  "Are you a masseuse? Because you're about to work out my knots.",
  "Do you have a shovel? Because I'm digging this hole deeper.",
  "Are you Spotify? Because I want to put you on repeat all night.",
  "Is your name Tesla? Because you're electric and I want to charge up.",
  "Are you a thermometer? Because I want to put you in my mouth.",
  "Do you work at an aquarium? Because you're about to see my sea cucumber.",
  "Are you a baseball? Because I want to hit a home run with you.",
  "Is your bed broken? Because I want to nail it for you.",
  "Are you a mechanic? Because I've got something that needs servicing.",
  "Do you like elevators? Because I want to go down on you.",
  "Are you a gym membership? Because I want to work you out daily.",
  "Is your name Visa? Because you're everywhere I want to be.",
  "Are you a vaccine? Because I need a shot of you.",
  "Do you like buffets? Because I want to eat you all night long.",
  "Are you a doorknob? Because everyone gets a turn.",
  "Is your name Domino's? Because I want a pizza you now.",
  "Are you WiFi? Because I'm feeling a strong connection to your hotspot.",
  "Do you work at Burger King? Because you can have it your way.",
  "Are you a test? Because I want to take you seriously.",
  "Is your last name Gillette? Because you're the best I can get.",
  "Are you a guitar? Because I want to play you all night long.",
  "Do you work at Nike? Because you make me just do it.",
  "Are you a zipper? Because I want to pull you down.",
  "Is your name Winter? Because you're coming.",
  "Are you a socket? Because I want to plug in.",
  "Do you like Netflix? Because I want to Netflix and actually chill.",
  "Are you a belt? Because you're holding up well.",
  "Is your body a Visa? Because I want to use it everywhere.",
  "Are you a model? Because I want to see you in less.",
  "Do you work at Build-A-Bear? Because I want to stuff you.",
  "Are you a skateboard? Because I want to ride you.",
  "Is your name Twitter? Because I want to follow you home.",
  "Are you a game? Because I want to play.",
  "Do you like puzzles? Because I want to figure you out piece by piece.",
  "Are you a phone? Because I want to tap you all night.",
  "Is your body an exam? Because I want to study every inch.",
  "Are you a lock? Because I have the key.",
  "Do you work at Popeyes? Because you're giving me a boner.",
  "Are you a blanket? Because I want you all over me.",
  "Is your name WiFi? Because I'm connecting.",
  "Are you a car? Because I want to rev your engine.",
  "Do you like tacos? Because I want to taco 'bout getting in your shell.",
  "Are you a printer? Because I want to feed you paper.",
  "Is your body a temple? Because I want to worship every inch.",
  "Are you an elevator? Because I want to go up and down.",
  "Do you work at a bakery? Because I want your buns.",
  "Are you a seatbelt? Because I need to buckle you.",
  "Is your name Bluetooth? Because I'm trying to pair.",
  "Are you a couch? Because I want to crash on you.",
  "Do you like sledding? Because I want to slide into you.",
  "Are you an onion? Because you're making me want to cry tears of joy.",
  "Is your body a menu? Because I want to taste everything.",
  "Are you a vending machine? Because you've got all the snacks.",
  "Do you work at a gym? Because you're giving me a workout.",
  "Are you a stoplight? Because I stop for you.",
  "Is your name Amazon? Because you have everything I want.",
  "Are you a video game? Because I want to play you on hard mode.",
  "Do you like swimming? Because I want to dive in.",
  "Are you a pole? Because I want to dance around you.",
  "Is your body a Ferrari? Because I want to take you for a ride.",
  "Are you a lottery ticket? Because I just hit the jackpot.",
  "Do you work at a car wash? Because you're making me wet.",
  "Are you a stapler? Because you're holding it together.",
  "Is your name Intel? Because you're inside.",
  "Are you a bicycle? Because I want to ride you all day.",
  "Do you like roller skating? Because I want to go all night.",
  "Are you a flashlight? Because you turn me on.",
  "Is your body a playground? Because I want to play.",
  "Are you a mirror? Because I can see myself on you.",
  "Do you work at Taco Bell? Because I want to make a run for the border with you.",
  "Are you an app? Because I want to download you.",
  "Is your name Nike? Because I want to just do you.",
  "Are you a furnace? Because you're hot and I want to turn you up.",
  "Do you like bowling? Because I want to score with you.",
  "Are you a ladder? Because I want to climb you.",
  "Is your body a remote? Because I want to press all your buttons.",
  "Are you a smoke alarm? Because you're hot and loud.",
  "Do you work at FedEx? Because I want to ship us.",
  "Are you a treadmill? Because I want to work you out.",
  "Is your name Adobe? Because you're creative and I want to explore.",
  "Are you a hot tub? Because I want to get in.",
  "Do you like racing? Because I want to finish first.",
  "Are you a credit card? Because I want to swipe you.",
  "Is your body a library? Because I want to check you out repeatedly.",
  "Are you a convertible? Because I want to put the top down.",
  "Do you work at IKEA? Because I want to assemble something with you.",
  "Are you a motorcycle? Because I want to ride you hard.",
  "Is your name JavaScript? Because you make everything dynamic.",
  "Are you a diving board? Because I want to take the plunge.",
  "Do you like camping? Because I want to pitch a tent.",
  "Are you a traffic cone? Because I want to knock you over.",
  "Is your body a casino? Because I'm going all in.",
  "Are you a playlist? Because I want to put you on shuffle.",
  "Do you work at Costco? Because you're a sample I want the whole package of.",
  "Are you a punching bag? Because I want to work you over.",
  "Is your name Apple? Because I want to take a byte.",
  "Are you a carnival ride? Because I want to go multiple times.",
  "Do you like hiking? Because I want to reach your peak.",
  "Are you a scratch-off? Because I want to see what's underneath.",
  "Is your body a mansion? Because I want to explore every room.",
  "Are you a turntable? Because I want to spin you.",
  "Do you work at Chipotle? Because I want to unwrap you.",
  "Are you a bouncy castle? Because I want to jump on you.",
  "Is your name Chrome? Because you're compatible with everything.",
  "Are you a pool table? Because I want to sink some balls.",
  "Do you like volleyball? Because I want to serve you.",
  "Are you a drum? Because I want to bang you all night.",
  "Is your body a smartphone? Because I can't put you down.",
  "Are you a waterslide? Because I want to go down.",
  "Do you work at Home Depot? Because you've got the tools.",
  "Are you a jackpot? Because I want to hit you.",
  "Is your name Pandora? Because I want to open you up.",
  "Are you a speed bump? Because I want to slow down on you.",
  "Do you like jet skiing? Because I want to ride the waves with you.",
  "Are you a piñata? Because I want to break you open.",
  "Is your body a dance floor? Because I want to get down.",
  "Are you a coin? Because I want to flip you.",
  "Do you work at Victoria's Secret? Because I want to unlock you.",
  "Are you a joystick? Because I want to play.",
  "Is your name Tesla? Because you're electric and I want a charge.",
  "Are you a shopping cart? Because I want to push you around.",
  "Do you like skiing? Because I want to hit the slopes with you.",
  "Are you a speaker? Because I want to turn up your volume.",
  "Is your body a amusement park? Because I want to ride everything.",
  "Are you a scratch card? Because I want to reveal what's hidden.",
  "Do you work at Target? Because you're my bullseye.",
  "Are you a zip line? Because I want to ride you from top to bottom.",
  "Is your name Snapchat? Because I want to see your streaks.",
  "Are you a swimming pool? Because I want to do a cannonball.",
  "Do you like paintball? Because I want to shoot my shot.",
  "Are you a basketball hoop? Because I want to score.",
  "Is your body a restaurant? Because I want to eat in.",
  "Are you a surfboard? Because I want to ride you in the waves.",
  "Do you work at Whole Foods? Because I want the organic experience.",
  "Are you a trampoline park? Because I want to bounce around with you.",
  "Is your name Instagram? Because I want to double tap that.",
  "Are you a waterbed? Because I want to make waves.",
  "Do you like boxing? Because I want to go a few rounds.",
  "Are you a scratch post? Because cats aren't the only ones who want to use you.",
  "Is your body a buffet? Because I want seconds and thirds.",
  "Are you a hammock? Because I want to lay in you all afternoon.",
  "Do you work at AT&T? Because you've got great coverage.",
  "Are you a slip-n-slide? Because I want to get wet and wild.",
  "Is your name Reddit? Because I want to upvote you.",
  "Are you a mechanical bull? Because I want to ride you for 8 seconds.",
  "Do you like go-karts? Because I want to take you for a spin.",
  "Are you a bowling alley? Because I want to strike.",
  "Is your body a laptop? Because I want to open you up and get to work.",
  "Are you a gondola? Because I want a romantic ride.",
  "Do you work at Best Buy? Because you're the best I can buy.",
  "Are you a merry-go-round? Because I want to go round and round.",
  "Is your name Uber? Because I want to request a ride.",
  "Are you a foam pit? Because I want to dive in.",
  "Do you like fishing? Because I want to catch and release... multiple times.",
  "Are you a massage chair? Because I want to sit on you and relax.",
  "Is your body an escape room? Because I want to figure you out.",
  "Are you a lazy river? Because I want to float with you all day.",
  "Do you work at a car dealership? Because I want to test drive.",
  "Are you a rope swing? Because I want to swing into action.",
  "Is your name YouTube? Because I could watch you all day.",
  "Are you a wave pool? Because I want to make waves with you.",
  "Do you like archery? Because I want to hit the target.",
  "Are you a keg? Because I want to tap that.",
  "Is your body a playlist? Because I want to hit repeat.",
  "Are you a climbing wall? Because I want to reach the top.",
  "Do you work at a spa? Because I need your special treatment.",
  "Are you a ball pit? Because I want to dive right in.",
  "Is your name Pinterest? Because I want to pin you down.",
  "Are you a foam roller? Because I want to work out my knots on you.",
  "Do you like tubing? Because I want to ride the river with you.",
  "Are you a hammock? Because I want to swing both ways.",
  "Is your body a Vegas casino? Because what happens with you stays with you.",
  "Are you a chairlift? Because I want you to take me to the top.",
  "Do you work at a juice bar? Because I want to squeeze.",
  "Are you a race track? Because I want to go fast.",
  "Is your name TikTok? Because I'm hooked.",
  "Are you a water park? Because I want to get soaked.",
  "Do you like bungee jumping? Because I want to take the leap with you.",
  "Are you a photo booth? Because I want multiple shots.",
  "Is your body a resort? Because I want the all-inclusive package.",
  "Are you a Ferris wheel? Because I want to go around with you.",
  "Do you work at Sephora? Because I want to sample everything.",
  "Are you a ski lift? Because you're taking me higher.",
  "Is your name Discord? Because I want to join your server.",
  "Are you a steam room? Because it's getting hot.",
  "Do you like parasailing? Because I want to be lifted up with you.",
  "Are you a sandbox? Because I want to play in you.",
  "Is your body a cruise ship? Because I want the full voyage.",
  "Are you a zipline? Because I want the thrill ride.",
  "Do you work at the Apple Store? Because I want a genius appointment.",
  "Are you a mudslide? Because I want to get dirty.",
  "Is your name Twitch? Because I want to subscribe.",
  "Are you a bounce house? Because I want to jump around.",
  "Do you like whitewater rafting? Because I want to ride the rapids with you.",
  "Are you a karaoke machine? Because I want to duet.",
  "Is your body a theme park? Because I want the fast pass.",
  "Are you a teacup ride? Because I want to spin with you.",
  "Do you work at the DMV? Because I want to get tested by you.",
  "Are you a salt lamp? Because you're making everything better.",
  "Is your name Spotify Premium? Because I want the uninterrupted experience.",
  "Are you a punching bag? Because you can take it.",
  "Do you like zorbing? Because I want to roll around with you.",
  "Are you a smoothie? Because I want to consume you.",
  "Is your body a members-only club? Because I want access.",
  "Are you a pogo stick? Because I want to bounce.",
  "Do you work at Lululemon? Because I want the stretch.",
];

export type PickupLineCategory = 'flirty' | 'poetic' | 'bold';

export const getRandomPickupLines = (): { line: string; category: PickupLineCategory }[] => {
  const flirty = flirtyLines[Math.floor(Math.random() * flirtyLines.length)];
  const poetic = poeticLines[Math.floor(Math.random() * poeticLines.length)];
  const bold = boldLines[Math.floor(Math.random() * boldLines.length)];

  return [
    { line: flirty, category: 'flirty' },
    { line: poetic, category: 'poetic' },
    { line: bold, category: 'bold' },
  ];
};
